<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ProgChecklist.Core\ProgChecklist.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\content\topics.json" Link="content\topics.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
